adjective = input("Write an adjective:")
animal = input("Write an animal:")
verb = input("Write a verb:")
exclamation = input("Write an exclamation:")
verb2 = input ("Write a verb:")
verb3 = input("Write a verb:")
print("")
print("Your story is:")
print(" ")
print("The other day, I was really in trouble. It all started when I saw a very")
print(f"{adjective} {animal} {verb} down the hallway."),print(f"{exclamation.capitalize()}!""I yelled. But all")
print(f"I could think todo was to {verb2} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb3} right in front of my family.")
