first = input ("What is your first name? ")
last = input ("What is your last name? ")
job = input ("What is your job title? ")
ID = input ("What is your ID number? ")
email = input ("What is your e-mail? ")
phone = input ("What is your phone number?")
hair = input ("What is your hair color? ")
eyes = input ("What is the color of your eyes? ")
month = input ("Month you started? ")
training = input ("Completed additional training? ")
print("The ID Card is:")
print("----------------------------------------")
print(last.upper() + ", " + first.capitalize())
print(job.title())
print("ID: " + ID)
print(" ")
print(email.lower())
print(phone)
print(" ")
print(f"Hair:  {hair.capitalize():15} Eyes: {eyes.capitalize()}")
print(f"Month:  {month.capitalize():14} Training: {training.capitalize()}")
print("----------------------------------------")
